title: InCube Core Library
email: info@incubegroup.com
description: >- # this means to ignore newlines until "baseurl:"
  Functional Data Types and Collection Extensions for C#
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://code.incubegroup.com" # the base hostname & protocol for your site, e.g. http://example.com

github_username: MartinMarciniszyn

markdown: kramdown
theme: jekyll-theme-cayman
logo: incube-logo.png

plugins:
  - jekyll-seo-tag

google_site_verification: "CKqiaxvuuOdZprfMSB3FtG7KdJO_DefkwjIUN1pQJGg"
